export const CLOSE_TOAST = "CLOSE_TOAST";
export const OPEN_AND_SET_TOAST_CONTENT = "OPEN_AND_SET_TOAST_CONTENT";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_AND_SET_MODAL_CONTENT = "OPEN_AND_SET_MODAL_CONTENT";
export const CLOSE_LOADER = "CLOSE_LOADER";
export const OPEN_LOADER = "OPEN_LOADER";
export const SAVE_TOKEN = "SAVE_TOKEN";
